# -*- coding: utf-8 -*-
"""A. Nunez - End-to-End Machine Learning with CRISP-DM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1re2saAoFg25pnBv08uVwTgAkjDigkk8y

#Anthony R. Nuñez
"""

!pip install kmodes

from kmodes.kmodes import KModes
import pandas as pd

df=pd.read_csv("/content/titanic (1).csv")

df.head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

# Drop 'Name' as it's not a direct feature for prediction
df_titanic = df.drop(columns=['Name'])

# Define features (X) and target (y)
X = df_titanic.drop('Survived', axis=1)
y = df_titanic['Survived']

# Identify numerical and categorical features
numerical_features = ['Age', 'Fare', 'sibspouse', 'parentchild']
categorical_features = ['Pclass', 'Sex']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the full pipeline with preprocessor and a classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)

"""Understanding factors that predict survival can be incredibly valuable. This prediction allows for insights into risk factors and can potentially inform safety protocols or resource allocation in similar disaster scenarios in the future."""

print(f"Original shape of df: {df.shape}")
df.dropna(inplace=True)
print(f"Shape of df after dropping missing values: {df.shape}")

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

# Drop 'Name' as it's not a direct feature for prediction
df_titanic = df.drop(columns=['Name'])

# Define features (X) and target (y)
X = df_titanic.drop('Survived', axis=1)
y = df_titanic['Survived']

# Identify numerical and categorical features
numerical_features = ['Age', 'Fare', 'sibspouse', 'parentchild']
categorical_features = ['Pclass', 'Sex']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create the full pipeline with preprocessor and a classifier
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)

!pip install streamlit
!streamlit hello